use_lockfile = false

[project]
name = "ghqc"
r_version = "4.4"

repositories = [
    { alias = "PPM", url = "https://packagemanager.posit.co/cran/latest" },
    { alias = "PRISM", url = "https://prism.a2-ai.cloud/rpkgs/nimbus/2025.08" }
]
dependencies = [
    "devtools",
    "rextendr",
    { name = "ghqc", path = ".", install_suggestions = true, dependencies_only = true },
]
